#ifndef BLADE_STANDARD_H
#define BLADE_STANDARD_H

extern CREATE_MODULE_LOADER(base64);
extern CREATE_MODULE_LOADER(date);
extern CREATE_MODULE_LOADER(io);
extern CREATE_MODULE_LOADER(math);
extern CREATE_MODULE_LOADER(os);
extern CREATE_MODULE_LOADER(socket);
extern CREATE_MODULE_LOADER(hash);
extern CREATE_MODULE_LOADER(json);
extern CREATE_MODULE_LOADER(sqlite);
extern CREATE_MODULE_LOADER(reflect);
extern CREATE_MODULE_LOADER(array);
extern CREATE_MODULE_LOADER(process);
extern CREATE_MODULE_LOADER(struct);
extern CREATE_MODULE_LOADER(thread);

#endif // BLADE_STANDARD_H
