#ifndef BLADE_STANDARD_H
#define BLADE_STANDARD_H


extern CREATE_MODULE_LOADER(base64);
extern CREATE_MODULE_LOADER(date);
extern CREATE_MODULE_LOADER(io);
extern CREATE_MODULE_LOADER(math);
extern CREATE_MODULE_LOADER(os);
extern CREATE_MODULE_LOADER(socket);
extern CREATE_MODULE_LOADER(hash);

#endif // BLADE_STANDARD_H
