#!-- This file is autogenerated by scripts/ast.b
/**
 * base Defn class
 */
class Defn {
}

/**
 * Doc Defn representation
 */
class DocDefn < Defn {

  /**
   * DocDefn(data)
   * @constructor 
   */
  DocDefn(data) {
    self.data = data
  }

  @to_json() {
    return {
      type: 'DocDefn',
      data: self.data,
    }
  }
}

