#!/bin/bash

if [[ ! $(command -v blade) ]]; then
  echo "Blade is not installed or not in path."
  exit 1
fi

BLADE_EXE=`which blade`

exec $BLADE_EXE "/Users/mcfriendsy/c/blade/blade/apps/qi/cli.b" "$@"
