#ifndef BLADE_BSTRING_H
#define BLADE_BSTRING_H

#include "common.h"
#include "native.h"
#include "vm.h"

#define DECLARE_STRING_METHOD(name) DECLARE_METHOD(string##name)

DECLARE_STRING_METHOD(length);
DECLARE_STRING_METHOD(upper);
DECLARE_STRING_METHOD(lower);
DECLARE_STRING_METHOD(case_fold);
DECLARE_STRING_METHOD(is_alpha);
DECLARE_STRING_METHOD(is_alnum);
DECLARE_STRING_METHOD(is_number);
DECLARE_STRING_METHOD(is_lower);
DECLARE_STRING_METHOD(is_upper);
DECLARE_STRING_METHOD(is_space);
DECLARE_STRING_METHOD(trim);
DECLARE_STRING_METHOD(ltrim);
DECLARE_STRING_METHOD(rtrim);
DECLARE_STRING_METHOD(join);
DECLARE_STRING_METHOD(split);
DECLARE_STRING_METHOD(index_of);
DECLARE_STRING_METHOD(starts_with);
DECLARE_STRING_METHOD(ends_with);
DECLARE_STRING_METHOD(count);
DECLARE_STRING_METHOD(to_number);
DECLARE_STRING_METHOD(to_list);
DECLARE_STRING_METHOD(lpad);
DECLARE_STRING_METHOD(rpad);
DECLARE_STRING_METHOD(match);
DECLARE_STRING_METHOD(matches);
DECLARE_STRING_METHOD(replace);
DECLARE_STRING_METHOD(replace_with);
DECLARE_STRING_METHOD(to_bytes);
DECLARE_STRING_METHOD(ascii);
DECLARE_STRING_METHOD(compare);
DECLARE_STRING_METHOD(__iter__);
DECLARE_STRING_METHOD(__itern__);

#endif