#ifndef BLADE_BYTES_H
#define BLADE_BYTES_H

#include "common.h"
#include "native.h"
#include "vm.h"

#define DECLARE_BYTES_METHOD(name) DECLARE_METHOD(bytes##name)

DECLARE_NATIVE(bytes);
DECLARE_BYTES_METHOD(length);
DECLARE_BYTES_METHOD(append);
DECLARE_BYTES_METHOD(clone);
DECLARE_BYTES_METHOD(extend);
DECLARE_BYTES_METHOD(index_of);
DECLARE_BYTES_METHOD(pop);
DECLARE_BYTES_METHOD(remove);
DECLARE_BYTES_METHOD(reverse);
DECLARE_BYTES_METHOD(first);
DECLARE_BYTES_METHOD(last);
DECLARE_BYTES_METHOD(get);
DECLARE_BYTES_METHOD(split);
DECLARE_BYTES_METHOD(is_alpha);
DECLARE_BYTES_METHOD(is_alnum);
DECLARE_BYTES_METHOD(is_number);
DECLARE_BYTES_METHOD(is_lower);
DECLARE_BYTES_METHOD(is_upper);
DECLARE_BYTES_METHOD(is_space);
DECLARE_BYTES_METHOD(dispose);
DECLARE_BYTES_METHOD(to_list);
DECLARE_BYTES_METHOD(to_string);
DECLARE_BYTES_METHOD(__iter__);
DECLARE_BYTES_METHOD(__itern__);

#endif