#ifndef BLADE_DICTIONARY_H
#define BLADE_DICTIONARY_H

#include "common.h"
#include "native.h"
#include "vm.h"

#define DECLARE_DICT_METHOD(name) DECLARE_METHOD(dict##name)

DECLARE_DICT_METHOD(length);
DECLARE_DICT_METHOD(add);
DECLARE_DICT_METHOD(set);
DECLARE_DICT_METHOD(clear);
DECLARE_DICT_METHOD(clone);
DECLARE_DICT_METHOD(compact);
DECLARE_DICT_METHOD(contains);
DECLARE_DICT_METHOD(extend);
DECLARE_DICT_METHOD(get);
DECLARE_DICT_METHOD(keys);
DECLARE_DICT_METHOD(values);
DECLARE_DICT_METHOD(remove);
DECLARE_DICT_METHOD(is_empty);
DECLARE_DICT_METHOD(find_key);
DECLARE_DICT_METHOD(to_list);
DECLARE_DICT_METHOD(__iter__);
DECLARE_DICT_METHOD(__itern__);

#endif