#ifndef BLADE_FILE_H
#define BLADE_FILE_H

#include "native.h"
#include "object.h"

#define DECLARE_FILE_METHOD(name) DECLARE_METHOD(file##name)

DECLARE_NATIVE(file);
DECLARE_FILE_METHOD(exists);
DECLARE_FILE_METHOD(close);
DECLARE_FILE_METHOD(open);
DECLARE_FILE_METHOD(is_open);
DECLARE_FILE_METHOD(is_closed);
DECLARE_FILE_METHOD(read);
DECLARE_FILE_METHOD(gets);
DECLARE_FILE_METHOD(write);
DECLARE_FILE_METHOD(puts);
DECLARE_FILE_METHOD(number);
DECLARE_FILE_METHOD(is_tty);
DECLARE_FILE_METHOD(flush);
DECLARE_FILE_METHOD(stats);
DECLARE_FILE_METHOD(symlink);
DECLARE_FILE_METHOD(delete);
DECLARE_FILE_METHOD(rename);
DECLARE_FILE_METHOD(path);
DECLARE_FILE_METHOD(mode);
DECLARE_FILE_METHOD(name);
DECLARE_FILE_METHOD(abs_path);
DECLARE_FILE_METHOD(copy);
DECLARE_FILE_METHOD(truncate);
DECLARE_FILE_METHOD(chmod);
DECLARE_FILE_METHOD(set_times);
DECLARE_FILE_METHOD(seek);
DECLARE_FILE_METHOD(tell);

#endif