#ifndef BLADE_LIST_H
#define BLADE_LIST_H

#include "common.h"
#include "native.h"
#include "vm.h"

#define DECLARE_LIST_METHOD(name) DECLARE_METHOD(list##name)

DECLARE_LIST_METHOD(length);
DECLARE_LIST_METHOD(append);
DECLARE_LIST_METHOD(clear);
DECLARE_LIST_METHOD(clone);
DECLARE_LIST_METHOD(count);
DECLARE_LIST_METHOD(extend);
DECLARE_LIST_METHOD(index_of);
DECLARE_LIST_METHOD(insert);
DECLARE_LIST_METHOD(pop);
DECLARE_LIST_METHOD(shift);
DECLARE_LIST_METHOD(remove_at);
DECLARE_LIST_METHOD(remove);
DECLARE_LIST_METHOD(reverse);
DECLARE_LIST_METHOD(sort);
DECLARE_LIST_METHOD(contains);
DECLARE_LIST_METHOD(delete);
DECLARE_LIST_METHOD(first);
DECLARE_LIST_METHOD(last);
DECLARE_LIST_METHOD(is_empty);
DECLARE_LIST_METHOD(take);
DECLARE_LIST_METHOD(get);
DECLARE_LIST_METHOD(compact);
DECLARE_LIST_METHOD(unique);
DECLARE_LIST_METHOD(zip);
DECLARE_LIST_METHOD(zip_from);
DECLARE_LIST_METHOD(to_dict);
DECLARE_LIST_METHOD(__iter__);
DECLARE_LIST_METHOD(__itern__);

#endif