name: Default Linux and OSX Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ created ]

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        curl: ['sudo apt-get install libcurl4 libcurl4-openssl-dev && sudo apt-get build-dep libcurl4 && sudo ldconfig', 'brew install curl']

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ${{ matrix.curl }}
    - name: make
      run: make release
